### ISSUE TITLE
Range Seekbar

### ISSUE THREAD

**Issue by denmarie** [warkiz/IndicatorSeekBar#1]
Is it possible to make it a Range Seekbar with 2 thumbs ?

**Comment by warkiz** [comment]
Thank you for your concert. But have no such plan by now. But you can code by yourself basing on my code.

**Comment by warkiz** [comment]
hi, rangseekbar was on schedule list now. pls wait.

**Comment by rohitsharma181589** [comment]
any help, how I can achieve this.
