### ISSUE TITLE
新版本怎么设置只显示左右两侧的文字

### ISSUE THREAD

**Issue by zcm-hu** [warkiz/IndicatorSeekBar#102]
之前用的1.2.8版本，最近发现改了好多API，以前很多方法都没有了。
我之前用的 mSeekBar.getBuilder().setRightEndText(“”)设置值，请问下 新版本还有这个功能吗。
另外一个问题，动态设置min 和max 刻度文字没有更新

**Comment by zcm-hu** [comment]
目前 这样处理了，可以实现这样的效果
`String[] tickTexts = new String[mSeekBar.getTickCount()];
        for (int i = 0; i < tickTexts.length; i++) {
            if (i == 0) {
                tickTexts[i] = "0";
            } else if (i == tickTexts.length - 1) {
                tickTexts[i] = rightEndText;
            } else {
                tickTexts[i] = "";
            }
        }
        mSeekBar.customTickTexts(tickTexts);`

**Comment by warkiz** [comment]
hi@zcm-hu , 可以使用这个api  indicatorSeekBar.showBothEndsTickTextsOnly(true).前提是已经show了刻度文字.
