### ISSUE TITLE
Not working with data binding 

### ISSUE THREAD

**Issue by ArvindGithub2015** [warkiz/IndicatorSeekBar#103]
This is not working with data binding 
  app:isb_max="@{viewModel.maxValue}"

1.data binding error ****msg:Cannot find the setter for attribute 'app:isb_max' with parameter type android.databinding.ObservableField<java.lang.Float> on com.warkiz.widget.IndicatorSeekBar.

2.data binding error ****msg:Cannot find the setter for attribute 'app:isb_max' with parameter type android.databinding.ObservableField<java.lang.Integer> on com.warkiz.widget.IndicatorSeekBar.

**Comment by warkiz** [comment]
Sorry, It didn't provided all settter methods for each attributes on IndicattorSeekBar.

**Comment by atasoglou** [comment]
Why was this closed? You don't want to support data-binding?
