### ISSUE TITLE
现在的需求是isb_seek_smoothly为true的时候也不要自动autoAdjustThumb，所以多加了一个自定义属性 默认为true和你的默认值一样，如果有需求 只需要在配置下isb_is_auto_adjust_thumb这个属性为false就好了  望采纳

### ISSUE THREAD

**Issue by liulilei** [warkiz/IndicatorSeekBar#104]
现在的需求是isb_seek_smoothly为true的时候也不要自动autoAdjustThumb，所以多加了一个自定义属性 默认为true和你的默认值一样，如果有需求 只需要在配置下isb_is_auto_adjust_thumb这个属性为false就好了  望采纳

**Comment by liulilei** [comment]
private boolean autoAdjustThumb() {
        if (!mAutoAdjustThumb) {
            return false;
        }

**Comment by warkiz** [comment]
@liulilei 可以了, 提供了属性isb_thumb_adjust_auto = true 或者调用方法  setThumbAdjustAuto(boolean adjustAuto)

**Comment by JinJieGu** [comment]
虽然禁用了autoAdjustThumb但是setprogress后依然会调用getClosestIndex自动调整

**Comment by liulilei** [comment]
@JinJieGu 这个只需要在重新写一个setprogress 方法就好了
在自己的方法里面  直接把下面代码注释掉 即可
 //adjust to the closest tick's progress
        if (mTicksCount > 2) {
            mProgress = mProgressArr[getClosestIndex()];
        }
