### ISSUE TITLE
请问indicator在最左侧或最右侧能否不被挤压, 显示在seekbar范围之外, 左右预留出一些空间?

### ISSUE THREAD

**Issue by supremelife** [warkiz/IndicatorSeekBar#107]
int indicatorOffset;
        int arrowOffset;
        if (measuredWidth / 2 + thumbCenterX > mMeasuredWidth) {
            indicatorOffset = mMeasuredWidth - measuredWidth;
            arrowOffset = (int) (thumbCenterX - indicatorOffset - measuredWidth / 2);
        } else if (thumbCenterX - measuredWidth / 2 < 0) {
            indicatorOffset = 0;
            arrowOffset = -(int) (measuredWidth / 2 - thumbCenterX);
        } else {
            indicatorOffset = (int) (thumbCenterX - measuredWidth / 2);
            arrowOffset = 0;
        }

**Comment by warkiz** [comment]
抱歉，不支持这个的。
