### ISSUE TITLE
setProgress doesn't work when attr `isb_seek_smoothly` is true

### ISSUE THREAD

**Issue by daodao917** [warkiz/IndicatorSeekBar#113]
If I set `isb_seek_smoothly` true, then I use `setProgress` in java which doesn't work. Thumb will be located in the near tick. Is that right?

**Comment by Quelake** [comment]
I noticed the same thing, would appreciate a solution

**Comment by warkiz** [comment]
@daodao917 @daodao917 I had noticed this，and will be fixed it in this week.Many thanks for your feedback.
