### ISSUE TITLE
How to Show SpannableString as Progress Text?

### ISSUE THREAD

**Issue by chnouman** [warkiz/IndicatorSeekBar#121]

**Comment by warkiz** [comment]
@chnouman you can set a new indicator view and change this view you want(include a TEXT with SpannableString  )

seekBar.getIndicator().setContentView(yourView with SpannableString );
more detail you can see [demo.apk](https://github.com/warkiz/IndicatorSeekBar/blob/master/apk/demo.apk) with part of custom indicator.

**Comment by chnouman** [comment]
@warkiz  thanks a lot I'll check this out.
