### ISSUE TITLE
Always Show Indicator

### ISSUE THREAD

**Issue by bios90** [warkiz/IndicatorSeekBar#123]
How to show bubble indicator always.
Sorry but i cant find solve such a simple issue.
app:isb_indicator_stay="true" gives me error attribute not found.
Thanks.

**Comment by bios90** [comment]
Here is my XML code
`            <com.warkiz.widget.IndicatorSeekBar
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:isb_max="100"
                app:isb_min="0"
                app:isb_progress="0"
                app:isb_seek_smoothly="true"
                app:isb_ticks_count="0"
                app:isb_show_tick_marks_type="none"
                app:isb_tick_marks_size="0dp"
                app:isb_tick_marks_drawable="@mipmap/ic_launcher"
                app:isb_show_tick_texts="true"
                app:isb_tick_texts_size="15sp"
                app:isb_tick_texts_color="@color/myLightGray"
                app:isb_thumb_color="@color/myPink"
                app:isb_thumb_size="12dp"
                app:isb_show_indicator="circular_bubble"
                app:isb_indicator_color="@color/myPink"
                app:isb_indicator_text_color="@color/myWhite"
                app:isb_indicator_text_size="18sp"
                app:isb_track_background_color="@color/myLightGray"
                app:isb_track_background_size="2dp"
                app:isb_track_progress_color="@color/myPink"
                app:isb_track_progress_size="4dp" />`

**Comment by warkiz** [comment]
@bios90 Hi, version 2+ is a big change and will not compat with 1.0+,please update to 2.0+;

Always Show Indicator : 
<com.warkiz.widget.IndicatorStayLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content">
    
    <com.warkiz.widget.IndicatorSeekBar
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:isb_show_indicator="rectangle" 
        ....../>
    
</com.warkiz.widget.IndicatorStayLayout>

**Comment by PembaTamang** [comment]
I am using this in a constraint layout and it is not working


```
 <com.warkiz.widget.IndicatorStayLayout
            android:id="@+id/s"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:layout_constraintBottom_toBottomOf="@+id/textView9"
            app:layout_constraintEnd_toStartOf="@+id/imageView5"
            app:layout_constraintStart_toEndOf="@+id/textView9"
            app:layout_constraintTop_toTopOf="@+id/textView9">
            <com.warkiz.widget.IndicatorSeekBar
                android:id="@+id/seekBar"
                android:layout_width="0dp"
                android:layout_height="4dp"
                android:layout_marginStart="16dp"
                android:layout_marginEnd="16dp"
                app:isb_indicator_color="@color/colorPrimary"
                app:isb_indicator_text_color="@color/white"
                app:isb_indicator_text_size="18sp"
                app:isb_max="10"
                app:isb_min="1"
                app:isb_only_thumb_draggable="false"
                app:isb_progress="1"
                app:isb_seek_smoothly="true"
                app:isb_show_indicator="rectangle"
                app:isb_show_tick_texts="false"
                app:isb_thumb_color="@color/colorPrimary"
                app:isb_thumb_size="20dp"
                app:isb_tick_texts_color="@color/white"
                app:isb_tick_texts_size="15sp"
                app:isb_track_background_color="@color/white"
                app:isb_track_background_size="2dp"
                app:isb_track_progress_color="@color/colorPrimary"
                app:isb_track_progress_size="2dp" />
        </com.warkiz.widget.IndicatorStayLayout>
```

Android Studio 3.5
Build #AI-191.8026.42.35.5791312, built on August 9, 2019
JRE: 1.8.0_202-release-1483-b03 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

I am usingg it in a fragment and I am using the latest andoridx libraries.

**Comment by PembaTamang** [comment]
well I wrapped it by LinearLayout and it worked. I hope this helps someone. Thank you for this amazing library
