### ISSUE TITLE
设置了tickCount(5) 然后再用代码setProgress(87)会被自动计算

### ISSUE THREAD

**Issue by chenyang2580** [warkiz/IndicatorSeekBar#125]
我是用JAVA代码创建的VIew，MAX设置100 MIN设置0 然后五个Tick点。 代码设置setProgress(XX)值会被自动计算  设置setThumbAdjustAuto(false);也不好使没效果

**Comment by chenyang2580** [comment]
解决了 在 refreshSeekBarLocation() 方法中注释掉
mProgress = mProgressArr[getClosestIndex()];就行了
作者可不可以添加一个方法控制是否开启getClosestIndex()的方法

**Comment by warkiz** [comment]
@chenyang2580 感谢反馈，当前版本是使用seek_smoothly属性的实现平滑滑动的，但是漏处理setProgress（）方法。下个版本会添加。
