### ISSUE TITLE
seekbar setprogress in textlistener makes it snap

### ISSUE THREAD

**Issue by weshuiz** [warkiz/IndicatorSeekBar#127]
it apears setting the seekbar setprogress inside a textwatch listener makes it snap
i resume this is a bug?
as i have tried to set seekbar value inside the textwatch even listener snapped my thumb-button to the nearest point

also you may want to include
IndicatorSeekBar seekbar = (IndicatorSeekBar) findViewbyId(R.id.seekbar);
in your documentation about the seekbar listener?

**Comment by warkiz** [comment]
@weshuiz Hi， this is a bug and will be fixed in this week. Thanks

**Comment by weshuiz** [comment]
Great to hear thanks a lot
On 3 Dec 2018 3:46 AM, Chuang Guangquan <notifications@github.com> wrote:@weshuiz Hi， this is a bug and will be fixed in this week. Thanks
