### ISSUE TITLE
isb_seek_smoothly=‘’true‘’不起作用

### ISSUE THREAD

**Issue by hardyio** [warkiz/IndicatorSeekBar#130]
外层如果是ScrollView包裹的话，isb_seek_smoothly=‘’true‘’不起作用，不能流畅滑动

**Comment by hardyio** [comment]
外层如果是ScrollView包裹的话，isb_seek_smoothly=‘’true‘’不起作用，不能流畅滑动

**Comment by warkiz** [comment]
@hardyio 能否贴布局出来看看，我按照你说的来测试是ok的。

**Comment by hardyio** [comment]
不知道什么原因，我把代码贴进demo也是好的
