### ISSUE TITLE
Custom tick text does not seem to work.

### ISSUE THREAD

**Issue by daerimin** [warkiz/IndicatorSeekBar#134]
I have tried setting custom text via code, and in XML using @array.  Nothing seems to work.

Does this depend on setting the text format?  Because if so, in Kotlin I cannot use ${TICK_TEXT} because it complaints about "unresolved reference" since this format is used to access a variable.

Is there a fix?

**Comment by rokjsn** [comment]
Have this problem too. This is because your code is in Kotlin. Easy fix is in your activity/fragment:
`
 val seekBar = IndicatorSeekBar
                .with(this)
                .build()
Fail.fix(seekBar)
`

Fail class (must be java):
`
public class Fail {
    public static void fix(IndicatorSeekBar indicatorSeekBar) {
        indicatorSeekBar.setIndicatorTextFormat("${TICK_TEXT} YEY. It works");
    }
}`
