### ISSUE TITLE
How to set thumb to gone?

### ISSUE THREAD

**Issue by goffity** [warkiz/IndicatorSeekBar#137]
When I use "indicatorSeekBar.hideThumb(true);" progress bar will rounded.
![42722556-142d6880-8778-11e8-9c39-812b02851aee](https://user-images.githubusercontent.com/778547/50167283-69784200-031b-11e9-82ee-3809f0023c7a.png)

How can I set thumb like View.GONE. or like this
![screen shot 2561-12-18 at 23 22 12](https://user-images.githubusercontent.com/778547/50167464-ce339c80-031b-11e9-9da7-89e48f8ee572.png)

**Comment by warkiz** [comment]
@goffity hi , No support this by now because the track is drawing according to line , and can not to handle this line to different end of shape by now. Thanks
