### ISSUE TITLE
怎么实现类似ios 语音备忘录完整片段、现在编辑片段的切换动画效果

### ISSUE THREAD

**Issue by iweey** [warkiz/IndicatorSeekBar#14]
参见：
https://support.apple.com/en-us/HT206775

如果完整片段和现在编辑片段seekbar的话
怎么实现类似ios 语音备忘录完整片段、现在编辑片段的切换动画效果

**Comment by warkiz** [comment]
目前，在一个Indicatorseekbar对象上修改buildparams参数来刷新自身时，没有加动画效果，后期会考虑加上，或者你已经加上了可以pull request一下
