### ISSUE TITLE
app:isb_thumb_adjust_auto="false" doesn't work when we got a "always stay" indicator

### ISSUE THREAD

**Issue by joseRelvasF3m** [warkiz/IndicatorSeekBar#142]
Hi @warkiz ! I don't know if this is a problem of mine, but when we got the "always stay" indicator, the "app:isb_thumb_adjust_auto" doesn't work properly. Even if I got it at false, the app runs it like it's true. Do you know if this is a bug or a problem in my code? Thank you very much for the component! 🥇

**Comment by warkiz** [comment]
Hi , could you post you related layout for this issue?

**Comment by raghavsatyadev** [comment]
<com.warkiz.widget.IndicatorStayLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content">
                
                <com.warkiz.widget.IndicatorSeekBar
                    android:id="@+id/seek_video_resolution"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="8dp"
                    android:padding="10dp"
                    app:isb_indicator_color="@color/colorPrimary"
                    app:isb_indicator_text_color="@android:color/white"
                    app:isb_seek_smoothly="true"
                    app:isb_show_indicator="rounded_rectangle"
                    app:isb_show_tick_marks_type="oval"
                    app:isb_thumb_adjust_auto="false"
                    app:isb_thumb_color="@color/colorPrimary"
                    app:isb_tick_marks_color="@color/colorPrimary"
                    app:isb_tick_marks_ends_hide="true"
                    app:isb_ticks_count="7"
                    app:isb_track_progress_color="@color/colorPrimary"
                    app:layout_constraintEnd_toEndOf="parent"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintTop_toBottomOf="@+id/ed_video_title"
                    tools:isb_progress="50" />

            </com.warkiz.widget.IndicatorStayLayout>

**Comment by raghavsatyadev** [comment]
<com.warkiz.widget.IndicatorStayLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content">

                <com.warkiz.widget.IndicatorSeekBar
                    android:id="@+id/seek_video_resolution"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="8dp"
                    android:padding="10dp"
                    app:isb_indicator_color="@color/colorPrimary"
                    app:isb_indicator_text_color="@android:color/white"
                    app:isb_seek_smoothly="true"
                    app:isb_show_indicator="rounded_rectangle"
                    app:isb_show_tick_marks_type="oval"
                    app:isb_thumb_adjust_auto="false"
                    app:isb_thumb_color="@color/colorPrimary"
                    app:isb_tick_marks_color="@color/colorPrimary"
                    app:isb_tick_marks_ends_hide="true"
                    app:isb_ticks_count="7"
                    app:isb_track_progress_color="@color/colorPrimary"
                    app:layout_constraintEnd_toEndOf="parent"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintTop_toBottomOf="@+id/ed_video_title"
                    tools:isb_progress="50" />

            </com.warkiz.widget.IndicatorStayLayout>

**Comment by warkiz** [comment]
@raghavsatyadev Hi, I run your layout but it is fine on my device, so do you ？
@joseRelvasF3m  hi, I think something wrong happened on you code, I test this but it is fine, hope more detail about this, thanks.

**Comment by raghavsatyadev** [comment]
I faced this issue auto_adjust is false so user can switch to any progress via dragging the thumb, but label of progress always stay on fix tick e.g.
MIN = 0
MAX = 100
TICK_COUNT = 10
User Selection  = 55 
Indicator Label Shows = 60 or 50

**Comment by warkiz** [comment]
@raghavsatyadev try to use attr : app:isb_seek_smoothly="true" and app:isb_thumb_adjust_auto="false" ,hope this helpful for you.

**Comment by joseRelvasF3m** [comment]
@warkiz Hi warkiz, strangely it begans to work fine... and I didn't change anything on my code. Thank you!
