### ISSUE TITLE
SeekBar in RecyclerView, on last seekbar select content jumps to top.

### ISSUE THREAD

**Issue by Joran-Dob** [warkiz/IndicatorSeekBar#147]
First of all thanks for the great library.

Unfortunately, I ran into an issue, so in our app, we have a RecyclerView with on each list item an indicator seek bar. 

The seek bar works perfectly for all list items except the last when, when I click or drag the seek bar the RecyclerView jumps up or to the top.
ViewHolder Layout XML: 
```java
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical"
    >

  <TextView
      android:id="@+id/tvHIDDEN"
      android:layout_width="0dp"
      android:layout_height="wrap_content"
      android:layout_marginEnd="24dp"
      android:layout_marginStart="24dp"
      android:layout_marginTop="32dp"
      android:text="HIDDENHIDDENHIDDENHIDDENHIDDENHIDDENHIDDENHIDDENHIDDENHIDDENHIDDENHIDDENHIDDEN"
      android:textColor="#000000"
      android:textDirection="locale"
      app:layout_constraintEnd_toEndOf="parent"
      app:layout_constraintStart_toStartOf="parent"
      app:layout_constraintTop_toTopOf="parent"
      />
  <View
      android:id="@+id/vHIDDEN"
      android:layout_width="match_parent"
      android:layout_height="1dp"
      android:layout_marginBottom="8dp"
      android:layout_marginEnd="16dp"
      android:layout_marginStart="16dp"
      android:background="?android:attr/listDivider"
      android:visibility="gone"
      app:layout_constraintBottom_toBottomOf="parent"
      app:layout_constraintEnd_toEndOf="parent"
      app:layout_constraintStart_toStartOf="parent"
      />
  <LinearLayout
      android:id="@+id/llHIDDEN"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:layout_marginBottom="46dp"
      android:layout_marginEnd="16dp"
      android:layout_marginStart="16dp"
      android:layout_marginTop="46dp"
      android:orientation="vertical"
      android:layoutDirection="ltr"
      app:layout_constraintBottom_toTopOf="@+id/vHIDDEN"
      app:layout_constraintEnd_toEndOf="parent"
      app:layout_constraintStart_toStartOf="parent"
      app:layout_constraintTop_toBottomOf="@+id/tvHIDDEN"
      />
</androidx.constraintlayout.widget.ConstraintLayout>```


Viewholder SliderCode:


```
    View indicatorView = View.inflate(mContext, R.layout.custom_HIDDEN_indicator, null);
    ((TextView) indicatorView.findViewById(R.id.tvHIDDEN)).setText(
        TextThree);
    sbHIDDEN = IndicatorSeekBar
        .with(mContext)
        .showTickTexts(true)
        .tickTextsArray(tickList)
        .tickCount(5)
        .indicatorTopContentView(indicatorView)
        .trackProgressColor(mContext.getResources().getColor(R.color.ba_question_slider_grey))
        .indicatorColor(mContext.getResources().getColor(R.color.charcoalGrey))
        .trackBackgroundColor(mContext.getResources().getColor(R.color.ba_question_slider_grey))
        .tickMarksColor(mContext.getResources().getColor(R.color.ba_question_slider_tick_grey))
        .trackBackgroundSize(8)
        .trackProgressSize(8)
        .showTickMarksType(TickMarkType.OVAL)
        .showThumbText(true)
        .r2l(MindmarkerApplication.isRtl())
        .indicatorColor(Color.TRANSPARENT)
        .tickMarksSize(8)
        .thumbSize(20)
        .tickTextsSize(getFontSize(TextOne.length()))
        .showIndicatorType(IndicatorType.ROUNDED_RECTANGLE)
        .thumbColor(ContextCompat.getColor(mContext, R.color.branding_primary_light))
        .tickTextsColor(
            mContext.getResources().getColor(R.color.charcoalGrey))
        .progress(2)
        .max(5)
        .min(0)
        .build();

    IndicatorStayLayout indicatorStayLayout = new IndicatorStayLayout(mContext);
    indicatorStayLayout.attachTo(sbHIDDEN);

    llHIDDEN.addView(indicatorStayLayout);
    addedSlider = true;
    sbHIDDEN.setOnSeekChangeListener(new OnSeekChangeListener() {
      @Override public void onSeeking(SeekParams seekParams) {
        answerWasChanged = true;
        if (seekParams.progress == 3) {
          ((TextView) indicatorView.findViewById(R.id.tvProgress_CBSI)).setText(
             TextThree);
        } else if (seekParams.progress == 1) {
          ((TextView) indicatorView.findViewById(R.id.tvProgress_CBSI)).setText(
              TextTwo);
        } else if (seekParams.progress == 4) {
          ((TextView) indicatorView.findViewById(R.id.tvProgress_CBSI)).setText(
             TextFour);
        } else {
          ((TextView) indicatorView.findViewById(R.id.tvProgress_CBSI)).setText(
              (seekParams.progress == 0) ? TextOne : TextFive);
        }
      }

      @Override public void onStartTrackingTouch(IndicatorSeekBar seekBar) {

      }

      @Override public void onStopTrackingTouch(IndicatorSeekBar seekBar) {

      }
    });
```

**Comment by warkiz** [comment]
@Joran-Dob I test this but it seems find . Something wrong in other code？
