### ISSUE TITLE
Change position of Indicator to be below of SeekBar

### ISSUE THREAD

**Issue by seanghay** [warkiz/IndicatorSeekBar#153]
I was wondering if there's any way I can set the indicator to be below of the SeekBar.

I wanted to change the position of `text_ticks` to be above the SeekBar as well.

**Comment by Deba22** [comment]
I was also looking for this. @seanghay  did you find answer to this?

**Comment by seanghay** [comment]
> I was also looking for this. @seanghay did you find answer to this?

No, I haven't. I ended up using the current one.

**Comment by Deba22** [comment]
> > I was also looking for this. @seanghay did you find answer to this?
> 
> No, I haven't. I ended up using the current one.

ok. Thanks!
