### ISSUE TITLE
你好，弹出输入法或者输入法隐藏的时候，IndicatorSeekbar会受影响，会自动跑到最近的节点处。并且监听不到该变化。

### ISSUE THREAD

**Issue by jcsunran** [warkiz/IndicatorSeekBar#162]

**Comment by jcsunran** [comment]
不止输入法，好像只要是打开其他应用，IndicatorSeekbar就会受影响。

**Comment by ksc91u** [comment]
我不管有沒有打開其他應用或是鍵盤
IndicatorSeekBar 都會定時自己呼叫 onMeasure 然後亂跳, 或者是mProgress 會改變, 但是圓點的位置卻不會改變

**Comment by ksc91u** [comment]
應該是 

這裏
https://github.com/warkiz/IndicatorSeekBar/blob/c13d9513d91e467fbe6489dff5836e2b0aa15a24/indicatorseekbar/src/main/java/com/warkiz/widget/IndicatorSeekBar.java#L388

沒有像其他地方一樣判斷 mSeekSmoothly ?

**Comment by jcsunran** [comment]
thanks very much.  就是这块判断的原因。

**Comment by hekaidaqaz** [comment]
怎么还没改
