### ISSUE TITLE
指定进度无效，图片怎么替换？

### ISSUE THREAD

**Issue by chenyannan** [warkiz/IndicatorSeekBar#165]
分段带有节点的isb_ticks_count这种 指定进度运行起来，不是该在的进度，会默认选择靠近的一个点上。还有图片怎么换呢，就是每一个点的图都不一样

**Comment by warkiz** [comment]
@chenyannan 第一个问题可以尝试使用属性auto adjust=false试试
第二个问题，现在不支持更换每一个thumb的图片，只能使用同一张图片
