### ISSUE TITLE
顶上的显示一直在，滑动条上有刻度，但是滑动的时候不自动靠到相应的刻度上，好像不可以

### ISSUE THREAD

**Issue by renwfy** [warkiz/IndicatorSeekBar#166]
![image](https://user-images.githubusercontent.com/6526280/55883087-3f9f9f80-5bd8-11e9-86f4-0c974069905e.png)

如图显示，滑动到哪里就是哪里，不自动靠过去，可行吗？

**Comment by warkiz** [comment]
@renwfy 试试auto adjust =false属性

**Comment by qlang122** [comment]
![image](https://github.com/warkiz/IndicatorSeekBar/assets/16172815/99192f66-5edd-478e-8854-54438e962e29)
那个属性并不行，要改源码的这个地方
