### ISSUE TITLE
Indicator stays on the top of all Views?

### ISSUE THREAD

**Issue by kevinzo22** [warkiz/IndicatorSeekBar#17]
@warkiz first, many thanks for this library! It's a great!

Then, I have a left menu at my app, and when I open/swipe the menu/tab to the right, the bubbles appear over the tab while the rest of the seekbar is normally displayed (not seen, under the tab). Seems that the indicator is above/on top of all Views. Is that correct?

I have also a top toolbar displaying the name of the activity, and scrolling all the way down (I have a ScrollView), the indicator just disappears behind the top toolbar, which is perfect. Would be great achieved the same thing when I open my left menu. I hope you can get what I mean.

Just in case, I'm using a Google Pixel with Android 8.1.0 and the last version of you development -> 'com.github.warkiz.widget:indicatorseekbar:1.2.4'

Thanks in advance! :)

**Comment by warkiz** [comment]
@kevinzo22 hi, on lastest version , you can set the Indicator to show or hide on your open/swipe menu listener. When you open the menu/tab , you can call insicatorSseekbar.show()/update（）; after open，you can check the indicatorSseekbar is  covered by other view or not（indicatorUtils.isViewCovered( ) )，if covered , call forcehide() to dismiss. 
for example:
your menuListener.setOnOpen/CloseListener(){

              if (IndicatorUtils.isViewCovered(indicatorSeekBar)) {
                    indicatorSeekBar.getIndicator().forceHide();
                } else {
                    if (indicatorSeekBar.getIndicator().isShowing()) {
                        indicatorSeekBar.getIndicator().update();
                    } else {
                        indicatorSeekBar.getIndicator().show();
                    }
                }
}

hope this change could help you.
