### ISSUE TITLE
无法动态设置

### ISSUE THREAD

**Issue by chain911** [warkiz/IndicatorSeekBar#18]
当我在布局里面使用的时候，在代码里我需要请求网络获取到最小值和最大值，然后再设置progress,会出现问题，比如我请求网络后获取最小值1000，最大值5000，我要设置progress为最小值，也就是说指示器应该在起点位置，并且气泡是一直都存在的，这个时候就会出现问题，气泡和指示器有偏移，而且气泡上显示的数值并不是1000

**Comment by warkiz** [comment]
最新版本已经修复，谢谢反馈。
