### ISSUE TITLE
中文的刻度会显示不全

### ISSUE THREAD

**Issue by ybADMIN** [warkiz/IndicatorSeekBar#2]
1.中文和数字的刻度显示不全
2.isb_thumb_width 无效

**Comment by warkiz** [comment]
@ybADMIN 能否贴出xml看看？

**Comment by ybADMIN** [comment]
就是有中文和英文的一起显示的时候中文就不能显示全，应该是文字计算有点问题

**Comment by warkiz** [comment]
@ybADMIN 最新版本已修复，thx
