### ISSUE TITLE
No disabled state

### ISSUE THREAD

**Issue by Shahar2k5** [warkiz/IndicatorSeekBar#20]
Tried to disabled to seekbar using 
`setEnabled(false)`
or
`setActivated(false)`

But it does not affect the view.

The only thing that works, is `forbidUserToSeek`
but that leaves the view in a enable state (colors etc.)

Any way to make it greyed out so it will look disabled?

**Comment by warkiz** [comment]
@Shahar2k5 I will fix this in next version，thanks

**Comment by warkiz** [comment]
hi @Shahar2k5 Support this now.
