### ISSUE TITLE
Custom typeface

### ISSUE THREAD

**Issue by adriamt** [warkiz/IndicatorSeekBar#23]
Is it possible to add a custom typeface? 
I saw that you add the text to a TextPaint and this class has the method setTypeface, maybe if you add an attribute that could be the typeface it will be possible to use a custom typeface.

**Comment by warkiz** [comment]
@adriamt will add this attr. in next version, thanks

**Comment by warkiz** [comment]
@adriamt hi support this now.

**Comment by adriamt** [comment]
Thanks !! I will try it right now !

**Comment by adriamt** [comment]
Don't work for me.
I've updated the library version, and now I see the Typeface option and I'm doing this:
`foodQuantityIndicator.getBuilder().setTextTypeface(custom_font).apply();`
And I tried adding the labels at the same time like this:
`foodQuantityIndicator.getBuilder().setTextArray(indicatorLabels).setTextTypeface(custom_font).apply();`

And nothing happens, it keep showing the default typeface.

**Comment by warkiz** [comment]
@adriamt hi, Now is ok, please use the newest version again.Many thanks for your feedback.

**Comment by adriamt** [comment]
Now it works Perfect!! Thanks !!
