### ISSUE TITLE
IndicatorSeekBar popUp window in vertical mode

### ISSUE THREAD

**Issue by mohammadtazehkar** [warkiz/IndicatorSeekBar#24]
i need to use IndicatorSeekBar in vertical mode so i set `android:rotation="-90"` but indicator popup window does not move with SeekBar in vertical and it move in horizontal mode
this is what i use in my layout XML : 
```
    <com.warkiz.widget.IndicatorSeekBar
        android:id="@+id/SeekBarIndicator"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="16dp"
        app:isb_indicator_custom_layout="@layout/custom_indicator_rec"
        app:isb_indicator_type="custom"
        app:isb_progress="20"
        app:isb_indicator_stay="true"
        app:isb_show_indicator="true"
        app:isb_thumb_progress_stay="true"
        android:rotation="-90"/>
```
![screenshot_2018-01-25-14-01-42 1](https://user-images.githubusercontent.com/15542850/35383851-c25b9f10-01d8-11e8-8007-6e813a10d003.png)

**Comment by warkiz** [comment]
@mohammadtazehkar  this repo is not support vertical situation when show Indicator

**Comment by warkiz** [comment]
not support vertical situation
