### ISSUE TITLE
wrong initial state

### ISSUE THREAD

**Issue by lifeisdream** [warkiz/IndicatorSeekBar#25]
I'm using this component:
`
<com.warkiz.widget.IndicatorSeekBar
        android:id="@+id/soc_seek"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        app:isb_indicator_type="circular_bubble"
        app:isb_max="100"
        app:isb_min="0"
        app:isb_progress="60"
        app:isb_seek_bar_type="discrete_ticks_texts"
        app:isb_tick_num="6"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toEndOf="@+id/soc_chip"
        app:layout_constraintTop_toBottomOf="@+id/brake_chip"/>
`

On some devices, its rendered ok, but on sony tablet (Android 5.0.2) its rendered this way:

![image](https://user-images.githubusercontent.com/1473995/35392934-898fc1ae-01f4-11e8-89cf-90247a7430b7.png)

Is this a bug or I did something wrong?

**Comment by lifeisdream** [comment]
`
<com.warkiz.widget.IndicatorSeekBar
        android:id="@+id/soc_seek"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        app:isb_indicator_type="circular_bubble"
        app:isb_max="100"
        app:isb_min="0"
        app:isb_progress="75"
        app:isb_seek_bar_type="discrete_ticks_texts"
        app:isb_tick_num="5"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toEndOf="@+id/soc_chip"
        app:layout_constraintTop_toBottomOf="@+id/brake_chip"/>
`

with even ranges:
![image](https://user-images.githubusercontent.com/1473995/35393208-5ab7e16c-01f5-11e8-8315-6dd1134d8ea8.png)

**Comment by lifeisdream** [comment]
another example:
`
<com.warkiz.widget.IndicatorSeekBar
        android:id="@+id/soc_seek"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginEnd="16dp"
        android:layout_marginStart="8dp"
        android:layout_marginTop="24dp"
        app:isb_indicator_type="circular_bubble"
        app:isb_max="100"
        app:isb_min="0"
        app:isb_progress="75"
        app:isb_seek_bar_type="continuous_texts_ends"
        app:isb_tick_num="5"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toEndOf="@+id/soc_chip"
        app:layout_constraintTop_toBottomOf="@+id/brake_chip"/>
`

![image](https://user-images.githubusercontent.com/1473995/35393923-6745822a-01f7-11e8-85e4-a3461480d253.png)

**Comment by warkiz** [comment]
@lifeisdream hi, I think this is a bug in constraintlayout situation, will review this and fix in next version, Thank you

**Comment by lifeisdream** [comment]
and if i put it into grid layout : 
![image](https://user-images.githubusercontent.com/1473995/35447106-d41d5ab4-02c7-11e8-99e2-4d26cc14f22c.png)

the positioning is still wrong
![image](https://user-images.githubusercontent.com/1473995/35447125-e46971fa-02c7-11e8-975c-082f84154369.png)

**Comment by warkiz** [comment]
@lifeisdream hi , I check this but no this issue found，see my screenshot below . which version does you use？Can you offer more complete layout info for this issue？thanks.  Also, hope issue #3 is helpful to you.
![_20180128174308](https://user-images.githubusercontent.com/20285327/35480849-bc176194-0452-11e8-9422-bb78003efdba.png)
![_20180128174221](https://user-images.githubusercontent.com/20285327/35480850-bc4d822e-0452-11e8-8ec9-81c5009ed7ea.png)

**Comment by lifeisdream** [comment]
0dp helped for the last one, thanks! 
I will review the first case latter.
