### ISSUE TITLE
能不能去掉手指点击改变进度的功能

### ISSUE THREAD

**Issue by FunnyLee** [warkiz/IndicatorSeekBar#26]
大神你好，这个seekbar能不能去掉手指点击选择进度的效果？只能通过滑动来改变进度，而不能通过直接点击进度条改变进度？谢谢

**Comment by warkiz** [comment]
@FunnyLee 你好，下个版本考虑加上

**Comment by FunnyLee** [comment]
嗯嗯，Thanks

**Comment by warkiz** [comment]
@FunnyLee 最新版本已经加上此功能, 在xml或java代码设置touch_to_seek = false;
