### ISSUE TITLE
气泡指示器在设置mShowIndicator与mIndicatorStay为true之后不能hide

### ISSUE THREAD

**Issue by sosoph1123** [warkiz/IndicatorSeekBar#27]
项目中需要气泡指示器常在，但是整个IndicatorSeekBar不会从界面detach的情况下，只设置IndicatorSeekBar的 visiable为gone ，只要界面有变化，气泡指示器就会重新出来；
我看了下代码 ， 程序一直在调用
    @Override
    public void onGlobalLayout() {
        checkIndicatorLoc();
    }
而   private void checkIndicatorLoc() {
        if (mIndicator == null || !p.mShowIndicator) {
            return;
        }
        if (p.mIndicatorStay) {
            if (mIndicator.isShowing()) {
                mIndicator.update();
            } else {
                mIndicator.show();
            }
        } else {
            mIndicator.forceHide();
        }
    }
这样不管我之前是否  mIndicator.forceHide();在界面有更新的时候，气泡指示器都会出来； 请问这样的情况该怎么办；有没有对于mShowIndicator或者mIndicatorStay动态设置的方法

**Comment by sosoph1123** [comment]
怎么解决啊大神 没有办法么 还是没理解我的问题啊

**Comment by warkiz** [comment]
@sosoph1123 你好，已经修复，使用最新版本
