### ISSUE TITLE
Wrong tick labels after setProgress

### ISSUE THREAD

**Issue by albertmasDaH** [warkiz/IndicatorSeekBar#28]
Hi. Nice widget. 
I've found a problem after setProgress is called. The tick labels disappear, and the only way to solve it is defining a string array. By example, this fails:

`
IndicatorSeekBar seekbar = (IndicatorSeekBar) view.findViewById(R.id.seekBar);
seekbar.setProgress(5);`

This also fails:

`seekbar.getBuilder()
                .setMin(0)
                .setMax(10)
                .setTickNum(11)
                .setProgress(5)
                .apply();`

And this is my empirical solution:

`seekbar.getBuilder()
                .setMin(0)
                .setMax(10)
                .setTickNum(11)
                .setTextArray(R.array.slider_ticks_1_10)
                .setProgress(5)
                .apply();`

The example array is just a 0-10 string values.
The xml is defined as:

`<com.warkiz.widget.IndicatorSeekBar
            android:id="@+id/seekBar"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:paddingBottom="20dp"
            android:paddingTop="20dp"
            app:isb_clear_default_padding="false"
            app:isb_max="10"
            app:isb_min="0"
            app:isb_progress="1"
            app:isb_seek_bar_type="discrete_ticks_texts"
            app:isb_show_indicator="false"
            app:isb_text_color="@color/textColor"
            app:isb_text_size="@dimen/textsize_medium"
            app:isb_thumb_color="@color/colorAccentDark"
            app:isb_thumb_width="@dimen/ikdc_slider_thumb_width"
            app:isb_tick_color="@color/colorAccentDark"
            app:isb_tick_num="10"
            app:isb_tick_size="15dp"
            app:isb_tick_type="oval"
            app:isb_track_background_bar_size="10dp"
            app:isb_track_progress_bar_color="@color/colorAccent"
            app:isb_track_progress_bar_size="20dp"
            app:isb_track_rounded_corners="true" />
`

The seekbar is shown right if setProgress is not called.
I'm doing something wrong?

**Comment by warkiz** [comment]
@albertmasDaH thanks,Iwill fixe this in next version asap.

**Comment by warkiz** [comment]
hi @albertmasDaH I didn't find this issue using the layout you offered above. I put the layout on xml file and fiind the view to setProgerss(5),  the thick labels display good . It is the thick(15dp) labels is covered by progressTrack(20dp) ? Could you offer more layout info or screenshot or using steps to help me to find&fix this issue? thanks.

**Comment by albertmasDaH** [comment]
It's not related with any overlap. The labels show the numbers from 0 to 10 if setProgress is not called. But if it is called, labels appear as 0,0,...,0,10.
The seek bar is displayed in a fragment, and setProgress is called into the onCreateView method.

**Comment by warkiz** [comment]
hi @albertmasDaH  have fixed this , thanks

**Comment by Aye-Myat-Mon** [comment]
I can't set #min over 100. Although I set setMin(200), actually it sets 100.0. What's the problem ? help me!

**Comment by warkiz** [comment]
@Aye-Myat-Mon if the min is bigger than max，the min will be limited in max. So please check you max first.Check and set max before min.
