### ISSUE TITLE
incorrect Measurement when it was packed into a ConstraintLayout

### ISSUE THREAD

**Issue by hollylee** [warkiz/IndicatorSeekBar#3]
In this case, any margin left|right would truncate the IndicateSeekBar. See attached images and xml definitions.
![image](https://user-images.githubusercontent.com/925338/33553553-31f21566-d934-11e7-80a3-d2a91bb291b5.png)
![image](https://user-images.githubusercontent.com/925338/33553561-3889fdda-d934-11e7-8d5d-8ff6d60ac4f3.png)

**Comment by warkiz** [comment]
@hollylee I will review this and fix it in next version as soon as possible. Thank you.

**Comment by warkiz** [comment]
@hollylee bug fix and see the lastest version. thank

**Comment by warkiz** [comment]
@hollylee also should not have the match parent in constraintlayoutin this case

**Comment by warkiz** [comment]
@hollylee According to [the guideline of ConstraintLayout ](https://developer.android.google.cn/reference/android/support/constraint/ConstraintLayout.html)from android , you should use  weight = 0 to replace the match_parent.

**Comment by hollylee** [comment]
@warkiz It is not a problem. match_parent and wrap_content always keep correct semantics.

**Comment by hollylee** [comment]
@warkiz Even if using layout_width="0dp" in ConstraintLayout, the latest code still didn't work. See attachments.
![image](https://user-images.githubusercontent.com/925338/33967497-b2a12d84-e09e-11e7-9fd6-1d87e65be06d.png)
![image](https://user-images.githubusercontent.com/925338/33967514-bcbbcd4c-e09e-11e7-869c-94413ad37eef.png)

**Comment by warkiz** [comment]
@hollylee thanks for feedback again . now you can use the new Version v1.1.9 
and my ConstraintLayout version is the newest One(1.1.0-beta3). It is fine to display on my phone and studio .



![a](https://user-images.githubusercontent.com/20285327/34002209-fa37031a-e12c-11e7-9b93-595f3ba1c10b.png)

**Comment by hollylee** [comment]
@warkiz So it is the bug of contraintLayout itself?

**Comment by warkiz** [comment]
@hollylee Still have this problem after using the newest version ? See my screenshot above , mine is fine.

**Comment by hollylee** [comment]
@warkiz Using latest codes and constraintLayout-1.1.0-beta3 got things shown correctly. Thanks a lot.
