### ISSUE TITLE
Keyboard indicator issue

### ISSUE THREAD

**Issue by dhavalappspool** [warkiz/IndicatorSeekBar#31]
![capture](https://user-images.githubusercontent.com/36662357/36420138-0f9647ea-165a-11e8-8cb5-411433b7f312.PNG)

please Solve it.

**Comment by dhavalappspool** [comment]
please fast it.

**Comment by warkiz** [comment]
hi @dhavalappspool which version does you use ? I use the newest one but have no this issue.please provide more info about this,many thanks

**Comment by dhavalappspool** [comment]
I have to use latest version.

compile 'com.github.warkiz.widget:indicatorseekbar:1.2.9'

**Comment by warkiz** [comment]
@dhavalappspool this issue can't appear again on my phone ，please help offer more details，many thanks

**Comment by warkiz** [comment]
@dhavalappspool the lastest version has fixed this, thx.
