### ISSUE TITLE
Change seekbar progress from code with animation

### ISSUE THREAD

**Issue by srujanb** [warkiz/IndicatorSeekBar#32]
Enhancement:

I guess it would look much better if you can change the value of the seekbar with animation (just a smooth movement of the thumb rather than abrupt movement) when changed programatically.

**Comment by srujanb** [comment]
@warkiz Any insights on this? I hope you got my point.

**Comment by warkiz** [comment]
@srujanb nice suggestion. I will try this once feel free.
