### ISSUE TITLE
Bug: Using "seekbar.setMax()" programmatically should change the Thumb position after maxValue changes successfully but it does not 

### ISSUE THREAD

**Issue by srujanb** [warkiz/IndicatorSeekBar#33]
I am changing the maxValue of the `seekbar` using `seekbar.setMax()` in my java code. After I change the maxValue, I would expect the thumb position to be recalculated according to the new `max` value but it does not. 

For example, if my minValue is 0, maxValue is 100 and progress is 75, the thumb position should be at 3/4th of the length of the seekbar. Now when I change the maxValue to 150, I would expect the thumb to move to half the length of the seekbar but it wont. 

Currently I am using a workaround by calling `seekbar.setProgress(seekbar.getProgress())` after calling the `seekbar.setMax()` every time.

**Comment by warkiz** [comment]
hi @srujanb mine is fine , please see the gif below, and please make sure you have used the lastest versison : compile 'com.github.warkiz.widget:indicatorseekbar:1.2.9' 


![a](https://user-images.githubusercontent.com/20285327/36639072-80a621fc-1a3e-11e8-96ea-86bb16c4853c.gif)
