### ISSUE TITLE
Ticker shows a values less 

### ISSUE THREAD

**Issue by Yeboster** [warkiz/IndicatorSeekBar#35]
``            <com.warkiz.widget.IndicatorSeekBar
                app:isb_max="5"
                app:isb_min="0"
                app:isb_progress="0"
                app:isb_show_indicator="true"
                app:isb_indicator_type="circular_bubble"
                app:isb_indicator_text_size="14dp"
                app:isb_seek_bar_type="discrete_ticks"/>``
if I use this seekbar it shows a value less. For example here it should shows value from 0 to 5 so in total are 6. It shows 0,2,3,4,5 = 5, not 6. Without discrete ticks no problems here. Thank you for the custom seekbar, you saved my day :)

**Comment by warkiz** [comment]
just add one more attr, isb_tick_num =6, please try this. the wrong showing because of the default tick num is 5.
