### ISSUE TITLE
We are using IndicatorSeekBar in recyclerview item with navigation drawer and Indicator stays on the top of all Views ?

### ISSUE THREAD

**Issue by aakashy85** [warkiz/IndicatorSeekBar#36]
We are using IndicatorSeekBar in Recyclerview item with navigation drawer and Indicator stays on the top of all Views when we open the drawer?

Screen shot : -

![screenshot_20180307-163629](https://user-images.githubusercontent.com/25077436/37089228-df17f028-2225-11e8-96bb-40855dcc4df0.png)
![screenshot_20180307-175236](https://user-images.githubusercontent.com/25077436/37092266-31b2755a-2231-11e8-9684-baec029f00e2.png)

**Comment by warkiz** [comment]
@aakashy85 hi , sorry for late recently is busy. Now the lastest verion is supported this excelently, hope this library is helpful to you. thanks
