### ISSUE TITLE
Top Text

### ISSUE THREAD

**Issue by StanislavSergeev** [warkiz/IndicatorSeekBar#37]
Hello, Can I show Text Array to top of seek bar?
I don't need indicator now,
I only want to display top text array instead of current bottom texts array.
How can I do it?

**Comment by warkiz** [comment]
@StanislavSergeev hi, no support this feature by now.

**Comment by warkiz** [comment]
@StanislavSergeev It's ok now, pleaase my [another library](https://github.com/warkiz/TickSeekBar).
