### ISSUE TITLE
Not showing text when tickNum is 2

### ISSUE THREAD

**Issue by Abdugani-Temirbaev** [warkiz/IndicatorSeekBar#38]
In my code I have random numbers generated and added to seekBar, sometimes 2 numbers generated and the size of seekBar become two. The text under tick is not showing.
My code is:
`
final CharSequence[] months = {"60", "90"};
final int monthsLen = months.length;
depositPeriod_SeekBar.getBuilder()
.setTextArray(months)
.setTickNum(monthsLen)
.apply();
`

As you can see in the image below seekBar is not showing numbers? but it can drag and pass position correctly.

![SeekBar Image](https://user-images.githubusercontent.com/11554999/37279301-33f6302a-260c-11e8-9909-255d4e886e77.PNG)

**Comment by warkiz** [comment]
@Abdugani-Temirbaev hi, thanks for feedback，the lastest version is ok.
