### ISSUE TITLE
How to dynamically set the text of the indicator？

### ISSUE THREAD

**Issue by xjhh** [warkiz/IndicatorSeekBar#39]
I want to change the text on the indicator to percentage. Is there any way to change it?

**Comment by EstebanC02** [comment]
Have you tried this?

`app:isb_text_array="@array/seekbar`

```
<array name="seekbar_lugares">
        <item>5%</item>
        <item>10%</item>
        <item>20%</item>
        <item>50%</item>
</array>
```

**Comment by warkiz** [comment]
@xjhh @EstebanC02 hi, the lastest version is supported this easily. you could do this by java code：seekbar.setIndicatorTextFormat("${PROGRESS} %")，more details please refer to [the newest readme.md](https://github.com/warkiz/IndicatorSeekBar)

**Comment by juanlabrador** [comment]
Hi, for cases like format money #.###,00 I try but don't works
