### ISSUE TITLE
Feature - Customized Tick

### ISSUE THREAD

**Issue by niroj08** [warkiz/IndicatorSeekBar#41]
Can the tick be customized for selected and non selected.

Suppose, the progress is at 50 and at progress 0 and 25 tick should have different color while at progress 75 and 100 tick color will be different.

If this is possible please let me know.
I don't think I have any solution 
Right now there is isb_tick_drawable and isb_tick_color
I was looking for something like selector

How much customization can be done by self?

Thanks in advance.

**Comment by warkiz** [comment]
@niroj08 Hi , thanks for your suggestion, now the lastest version is support this now.
