### ISSUE TITLE
Is there any way to change the text style/color of the selected value?

### ISSUE THREAD

**Issue by poojakaluskar** [warkiz/IndicatorSeekBar#43]
<img width="331" alt="screen shot 2018-03-28 at 11 16 48 am" src="https://user-images.githubusercontent.com/12078962/38047526-727ffc26-3288-11e8-84a3-5426c35b6673.png">

As you can see the text color of the number "2" is blue.

**Comment by warkiz** [comment]
hi @poojakaluskar the lastest version is supported this now, thanks.
