### ISSUE TITLE
Feature: possibility to set ticks / values manually

### ISSUE THREAD

**Issue by akidee** [warkiz/IndicatorSeekBar#49]
... so the distance - `mSeekBlockLength` - may vary.
The API could be like this:
`... .setMax(200).setMin(0).addTick(0).addTick(10).addTick(50).addTick(190) ...`
This could be used in union with `setTickNum()`

**Comment by warkiz** [comment]
hi @akidee ,So sorry , not suport this , I hope this library is used in some comom situation.
