### ISSUE TITLE
分段显示不同的颜色怎么做呢，类似这样的

### ISSUE THREAD

**Issue by hedongBlog** [warkiz/IndicatorSeekBar#50]
![image](https://user-images.githubusercontent.com/18640149/38541023-6c057040-3cd0-11e8-84c4-ebf3a89a5389.png)

**Comment by warkiz** [comment]
你好，最新版本已经支持，具体使用方式可以参照最新版本的[readme说明](https://github.com/warkiz/IndicatorSeekBar).
