### ISSUE TITLE
setting font

### ISSUE THREAD

**Issue by bios90** [warkiz/IndicatorSeekBar#51]
Sorry for my noob questions.
1) in xml file we have app:isb_text_typeface="" . How to set font here from my res/font or asset/myfonts
2) will app:isb_text_typeface="" change font at the at isb_text_left_end and isb_text_right_end?

IndicatorSeekBar is awesome,Thank you)

**Comment by warkiz** [comment]
hi @bios90  Hope my answers helpful to you：
1. in the lastest version , you can do this by java code : seekbar,setTickTextsTypeface( Your typeface );
2. in the lastest version，yes.
thx.

**Comment by bios90** [comment]
You are awesome!Thanks!
