### ISSUE TITLE
padding

### ISSUE THREAD

**Issue by JustinChiang123** [warkiz/IndicatorSeekBar#52]
为什么默认会有padding ？ 怎么去掉 ？

**Comment by 13145201765** [comment]
Can you post the key code?II'll try my best to help you.

**Comment by 13145201765** [comment]
翻一下源代码吧嘿嘿,这个做的挺好的了,不过因为跟我需求不符合我就自己写了一个,我们的需要进度条渐变而且要带流水状动画的那种seekbar,还要实现案例里这种带数值的标签,可累惨了做了一天多才搞定

**Comment by warkiz** [comment]
@JustinChiang123 使用属性clearDefaultPadding= true就可以去掉了.,
