### ISSUE TITLE
手动设置进度后，就不显示最大值了，如下图

### ISSUE THREAD

**Issue by renwfy** [warkiz/IndicatorSeekBar#53]
好像上传不了图片：如下设置
              android:id="@+id/continuous"
             app:isb_indicator_stay="true"
            app:isb_indicator_type="circular_bubble"
            app:isb_max="100.0"
            app:isb_min="0.0"
            app:isb_progress="80.3"
            app:isb_progress_value_float="true"
            app:isb_seek_bar_type="continuous_texts_ends"
               
            //
            continuous.setProgress(23.6f);

**Comment by warkiz** [comment]
我复现不出来，麻烦告知一下怎么复现的？

**Comment by warkiz** [comment]
你好, 最新版本可以了，可以试试。
