### ISSUE TITLE
Reverse count not working

### ISSUE THREAD

**Issue by BacancyVishal** [warkiz/IndicatorSeekBar#59]
Hi 
This lib is awesome. grate work.
I have small issue please check.
Reverse count not working (not show count proper) like 
i set this value:
 app:isb_max="0"
 app:isb_min="10"

**Comment by warkiz** [comment]
@BacancyVishal Hi, it seem peculiar. I am so to tell you that the min value must be less than max's.

**Comment by BacancyVishal** [comment]
![selection_025](https://user-images.githubusercontent.com/36661927/40976103-b00d006e-68ea-11e8-9934-debf1d80f544.png)
i agree with you but i am showing seekbar like this.

**Comment by warkiz** [comment]
@BacancyVishal maybe you can custom the text array by setTickTextArray(arr), the arr ={10,9,8,7,6,5,4,3,2,1,0},  hope this helpful to you.thanks
