### ISSUE TITLE
又是编译不过，哥

### ISSUE THREAD

**Issue by W-quan** [warkiz/IndicatorSeekBar#61]
![default](https://user-images.githubusercontent.com/9608466/41011515-cfe9d742-696f-11e8-9081-dbcc70c7c131.png)

**Comment by warkiz** [comment]
@W-quan 库中用了隐藏的android API , 下载[android.jar ](https://github.com/warkiz/android-hidden-api/blob/master/android-27/android.jar)到本地\sdk\platforms\android-27\下替换掉原来的，重新编译。替换前注意备份。
