### ISSUE TITLE
博主，能不能把代码的版本再控制一下

### ISSUE THREAD

**Issue by zidanpiaoguo** [warkiz/IndicatorSeekBar#63]
种类怎么都合并了，变少了，而且最新的主线上的代码是错的、

**Comment by warkiz** [comment]
@zidanpiaoguo 这是v2版本，和v1相比代码变动比较大，v2种类精简了，但是兼容的情况比v1更多了。v1的最后一个版本的代码我tag出来了放在realese里面了，以后只维护v2了，因为v2已经全覆盖v1的功能了，并且更加丰富了，可以将v2重新checkout代码下来，别从v1的基础去更新。代码是对的。

**Comment by warkiz** [comment]
@zidanpiaoguo 如果checkout v2的代码下来，记得需要替换android.jar才能跑起来。库中用了隐藏的android API , 下载[ android.jar ](https://github.com/warkiz/android-hidden-api/blob/master/android-27/android.jar)到本地\sdk\platforms\android-27\下替换掉原来的，重新编译。替换前注意备份。

**Comment by zidanpiaoguo** [comment]
V2版本，我要在上部加单位应该怎么写？

**Comment by warkiz** [comment]
@zidanpiaoguo v1的方式还是可以适用在v2的，而且v2还增加了一种简单的方式，
例如你想在Idicator的进度progress后面加上 % , 那可以直接调用 seekbar.setIndicatorTextFormat("${PROGRESS} %");就可以了。具体的可以阅读[readme.md.](https://github.com/warkiz/IndicatorSeekBar/blob/master/README.md)

**Comment by zidanpiaoguo** [comment]
为什么我改成你的v2那些属性都找不到了呢，Error:error: attribute 'com.example.vicloth.mirror:isb_indicator_type' not found.还有，你的V1的代码放在哪个版本了，我一直没找到呢？

**Comment by zidanpiaoguo** [comment]
哦，你全部都放在外部了啊。

**Comment by warkiz** [comment]
@zidanpiaoguo 你可以理解为，v1和v2在使用上已经一样了，但是v1功能在v2上还是具备的，但是用起来和v1不一样，如果你以前用v1，想换成v2的话，就重新按照demo去写layout了。v2相对v1的改动是挺大的，但是也比v1好用。欢迎尝试。

**Comment by zidanpiaoguo** [comment]
我看了一下你的版本最高还是1.2.9 ，这应该是V1吧，但是和你贴的图不太一样，V2的XML不是<com.warkiz.widget.IndicatorSeekBar
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:isb_max="100"
    app:isb_min="-1.0"
    app:isb_progress="25"
    app:isb_seek_smoothly="true"
    app:isb_ticks_count="5"
    app:isb_show_tick_marks_type="oval"
    app:isb_tick_marks_size="13dp"
    app:isb_tick_marks_drawable="@mipmap/ic_launcher"
    app:isb_show_tick_texts="true"
    app:isb_tick_texts_size="15sp"
    app:isb_tick_texts_color="@color/color_blue"
    app:isb_thumb_color="@color/color_green"
    app:isb_thumb_size="20dp"
    app:isb_show_indicator="rounded_rectangle"
    app:isb_indicator_color="@color/color_gray"
    app:isb_indicator_text_color="@color/colorAccent"
    app:isb_indicator_text_size="18sp"
    app:isb_track_background_color="@color/color_gray"
    app:isb_track_background_size="2dp"
    app:isb_track_progress_color="@color/color_blue"
    app:isb_track_progress_size="4dp" />这样写嘛？

**Comment by warkiz** [comment]
V1.2.9 是v1的最后一个版本。是的，这个布局是v2
