### ISSUE TITLE
setProgress 后 track_progress 没有更新

### ISSUE THREAD

**Issue by W-quan** [warkiz/IndicatorSeekBar#65]
![default](https://user-images.githubusercontent.com/9608466/41082216-23c0ec66-6a60-11e8-8cb1-cbae66126cb4.png)

如图， 先用手拖拉，  点击 恢复按钮， setProgress恢复默认值， 出现track_progress 更新现象

**Comment by warkiz** [comment]
@W-quan 这个bug昨晚修复了，你应该用了昨晚之前的版本，试试最新版本看看。

**Comment by warkiz** [comment]
#62 应该和这个issue一样的问题。

**Comment by W-quan** [comment]
还有个问题， setProgress 不会触发OnSeekChangeListener的onSeeking

**Comment by warkiz** [comment]
是的，这个是个bug,感谢反馈。晚上更新版本修复。你在setProgresss( )方法中将 lastProgress = mProgress;放在 setSeekListener(false);下面一行应该就行了。

**Comment by warkiz** [comment]
@W-quan 最新版本ok了。

**Comment by W-quan** [comment]
thank you.
