### ISSUE TITLE
Some issue in library

### ISSUE THREAD

**Issue by shiv71** [warkiz/IndicatorSeekBar#67]
**1. First issue.**
There are some error in library IndicatorSeekBar, IndicatorStayLayout class. I download your code and try to run it give error in IndicatorSeekBar, IndicatorStayLayout file.

*a. In IndicatorStayLayout file:-** 
   error in line number 88 and code is-
```
layoutParams.setMargins(layoutParams.leftMargin, layoutParams.topMargin,
                    layoutParams.rightMargin, SizeUtils.dp2px(mContext, 2) - seekBar.getPaddingTop());
```
in this code mContext showing error

**b. In IndicatorSeekBar file : -**
 `colorStateList.getStates()` code showing error everywhere in file.

**2. Second issue.**
I add your library in my project gradle file like 
    implementation 'com.github.warkiz.widget:indicatorseekbar:2.0.3'
and it work fine but there is one issue.
Code is-
```
<com.warkiz.widget.IndicatorSeekBar
        android:id="@+id/seek_bar_new"
        android:layout_marginTop="20dp"
        android:layout_below="@+id/seekBarValue"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:isb_indicator_top_content_layout="@layout/custom_top_content_view_round"
        app:isb_progress="0"
        app:isb_show_indicator="rounded_rectangle"
        app:isb_show_tick_marks_type="divider"
        app:isb_thumb_color="@color/yello"
        app:isb_tick_marks_color="@color/yello"
        app:isb_indicator_color="@color/yello"
        app:isb_track_background_color="@color/yello"
        app:isb_track_progress_color="@color/yello"
        app:isb_ticks_count="30"
        app:isb_max="30"/>
```

When i getting indicator in below method it return null or when getting indicator direct IndicatorSeekBar it also return null but when i get indicator in onSeeking method some time it work fine but some time it return null.
 ```
@Override
            public void onStartTrackingTouch(IndicatorSeekBar seekBar) {
                seekBarValue.setVisibility(View.INVISIBLE);
              Indicator indicator = seekBar.getIndicator();
                View view1 = indicator.getContentView();
                TextView progressText = view1.findViewById(R.id.progressText);
                progressText.setText(seekBarValue.getText());


            }
```

**Comment by warkiz** [comment]
@shiv71 hi, fixed it, please use the lastest version , many thanks for feekback again.
