### ISSUE TITLE
I have any problem with proguard after add IndicatorSeekbar on my project

### ISSUE THREAD

**Issue by ahmaadyunus** [warkiz/IndicatorSeekBar#68]
I was added IndicatorSeekBar on my project. While, I wil generate signed APK. I have problem with proguard. here is the problem :

![capture](https://user-images.githubusercontent.com/10239339/41193097-368d85ec-6c32-11e8-8b27-3f35d04c73d1.JPG)

What should I do to fix it ?

**Comment by warkiz** [comment]
@ahmaadyunus Hi ,thanks for feedback, please add below text in proguard-rules.pro before generate signed APK. If it is working , please help close this issue, many thanks.
-dontwarn com.warkiz.widget.**

**Comment by ahmaadyunus** [comment]
thank you
