### ISSUE TITLE
同级添加其他控件，指示器显示不完善

### ISSUE THREAD

**Issue by YXY1109** [warkiz/IndicatorSeekBar#69]
http://ovxxegsj6.bkt.clouddn.com/1.png
项目中使用，可能包含其他控件，类似这样的情况要怎么修改了

**Comment by warkiz** [comment]
@YXY1109 感谢反馈，这可能是个bug，明天修复。

**Comment by warkiz** [comment]
@YXY1109 hi, 最新版本已经修复，thx.
