### ISSUE TITLE
app:isb_show_indicator="rounded_rectangle" 的 corners 大小如何设置？

### ISSUE THREAD

**Issue by W-quan** [warkiz/IndicatorSeekBar#70]
想设置小一点圆角大小

**Comment by warkiz** [comment]
@W-quan 这个还不支持设置，你可以自定义一个topContentView，背景的圆角大小你可以在view里自己限制。

**Comment by W-quan** [comment]
能不能增加这样的一个方法？如果用topContentView的话，动作似乎有点大

**Comment by warkiz** [comment]
@W-quan 下个版本看看加上，最近有点忙。

**Comment by warkiz** [comment]
@W-quan 这个还有问题，目前不开放这个属性。
