### ISSUE TITLE
数组越界

### ISSUE THREAD

**Issue by fearlesstrek** [warkiz/IndicatorSeekBar#71]
D AndroidRuntime: Shutting down VM
06-12 19:11:03.019  4432  4432 W System.err: java.lang.ArrayIndexOutOfBoundsException: length=31; index=-1
06-12 19:11:03.020  4432  4432 W System.err: 	at com.warkiz.widget.IndicatorSeekBar.setListener(IndicatorSeekBar.java:748)
06-12 19:11:03.020  4432  4432 W System.err: 	at com.warkiz.widget.IndicatorSeekBar.setProgress(IndicatorSeekBar.java:1022)
06-12 19:11:03.020  4432  4432 W System.err: 	at com.desay_svautomotive.settings.hmi.sound.SoundVolumeFragment$SettingsMusicContentObserver.onChange(SoundVolumeFragment.java:255)
06-12 19:11:03.020  4432  4432 W System.err: 	at android.database.ContentObserver.onChange(ContentObserver.java:130)
06-12 19:11:03.020  4432  4432 W System.err: 	at android.database.ContentObserver.onChange(ContentObserver.java:145)
06-12 19:11:03.020  4432  4432 W System.err: 	at android.database.ContentObserver$NotificationRunnable.run(ContentObserver.java:216)
06-12 19:11:03.020  4432  4432 W System.err: 	at android.os.Handler.handleCallback(Handler.java:739)
06-12 19:11:03.020  4432  4432 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-12 19:11:03.020  4432  4432 W System.err: 	at android.os.Looper.loop(Looper.java:135)
06-12 19:11:03.020  4432  4432 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5309)
06-12 19:11:03.020  4432  4432 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
06-12 19:11:03.020  4432  4432 W System.err: 	at java.lang.reflect.Method.invoke(Method.java:372)
06-12 19:11:03.020  4432  4432 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1249)
06-12 19:11:03.020  4432  4432 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1044)

**Comment by warkiz** [comment]
@fearlesstrek 用的最新版本？怎么触发的？

**Comment by warkiz** [comment]
@fearlesstrek 你这个版本应该不是最新的了，试试最新的。
