### ISSUE TITLE
How to remove the thumb drawables if we set the thumb drawable dynamically.

### ISSUE THREAD

**Issue by gaurav7891** [warkiz/IndicatorSeekBar#73]
Hi,
I have used the Indicator seekbar where i set the thumb drawable dynamically. After progress done to max limit i have to remove the thumb drawable.

**Comment by warkiz** [comment]
@gaurav7891 not support this now, you can't remove the drawable on this version, I will try to add this in next version. thanks

**Comment by warkiz** [comment]
Also, the thumb drawable you set was remove but the default thumb left, do you want to remove the default's together?

**Comment by gaurav7891** [comment]
![seekbar](https://user-images.githubusercontent.com/40208221/41331603-6dd0b5de-6ef7-11e8-91f2-db5d9209d84b.PNG)
Above is the snapshot of my implementation of Indicator seekbar. I just want to remove the drawable after progress complete.

**Comment by warkiz** [comment]
@gaurav7891 hi, please see the latest version, you can do this by seekbar.hideThumb(true); if it is helpful to you , please help closed the issue, thanks.
