### ISSUE TITLE
How to set step value

### ISSUE THREAD

**Issue by ImGokulM** [warkiz/IndicatorSeekBar#75]
I have set the minimum and maximum to 10000 to 100000 and I would like to increment value by **1000** instead of 1,2,3.... Is there any way to achieve it? Thanks!

**Comment by warkiz** [comment]
@ImGokulM try to set Ticks count to 11and seekbar will be split in 10 blocks, every bl ock is 1000 length.

**Comment by asknask** [comment]
> @ImGokulM try to set ticks count to 11and seekbar will be splited in 10 blocks, every block is 1000 length.

This doesn't solve the problem though. Step size isn't configurable?

I have too many steps between 100 and 5000 (100 step size).
