### ISSUE TITLE
how to make it snapping seek bar

### ISSUE THREAD

**Issue by abhishektiwarijr** [warkiz/IndicatorSeekBar#76]
I want to make it snapping, please suggest me.

**Comment by warkiz** [comment]
@abhishektiwarijr Hi , I can't understand what you said well.

**Comment by warkiz** [comment]
@abhishektiwarijr ？

**Comment by abhishektiwarijr** [comment]
Sorry, it's a snapping seekbar. i didn't see that.
Awesome library
