### ISSUE TITLE
如下图

### ISSUE THREAD

**Issue by fearlesstrek** [warkiz/IndicatorSeekBar#79]
我需要以下的样式，可是滑动的时候，在9和10之间，设置了isb_seek_smoothly=true，不会自动适配到10.
![image](https://user-images.githubusercontent.com/12731121/41497654-0f7f2028-718c-11e8-9180-e3913edc9972.png)
![image](https://user-images.githubusercontent.com/12731121/41497655-1d96b0e0-718c-11e8-8239-dc501ec6985d.png)

**Comment by warkiz** [comment]
用刚刚的最新版本，xml大概是这样：
 <com.warkiz.widget.IndicatorSeekBar
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:isb_max="10"
            app:isb_seek_smoothly="true"
            app:isb_show_indicator="circular_bubble"
            app:isb_show_tick_texts="true"
            app:isb_ticks_count="10" />
还需要在代码设置 seekbar.showBothTickTextsOnly(true);

**Comment by warkiz** [comment]
@fearlesstrek ok的话帮忙close这个issue.

**Comment by fearlesstrek** [comment]
感谢！
