### ISSUE TITLE
是否支持之定义背景，像普通seekbar一样

### ISSUE THREAD

**Issue by renwfy** [warkiz/IndicatorSeekBar#80]
是否支持之定义背景，像普通seekbar一样

**Comment by renwfy** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android" >

    
    <item
        android:id="@android:id/background"
        android:drawable="@drawable/game_progressbar_0"/>
    
    
    <item android:id="@android:id/progress">
        <clip android:drawable="@drawable/game_progressbar_30" />
    </item>

</layer-list>

**Comment by warkiz** [comment]
目前不支持的
