### ISSUE TITLE
Issue with alternate ticks

### ISSUE THREAD

**Issue by ankuranurag2** [warkiz/IndicatorSeekBar#82]
When building a seekbar programatically, using Builder class, I faced a strange issue. The progress chnages automatically on alternate ticks, when keyboard comes in focus. 

Assume you have ticks as:[0,2,4,6,8,10]. If i change the progress of seek bar to 6 and then click on any EditText & keyboard appears, the progress of seekbar is automatically changed to 8. This happens with ticks [2,6,10] but doesnt happen with ticks [0,4,8]. The issue is with alternate ticks.

**Comment by warkiz** [comment]
@ankuranurag2 do you use the latest version?

**Comment by ankuranurag2** [comment]
Yes i am using the latest version.

**Comment by ankuranurag2** [comment]
Also if i use  the following code,when i have ticks as [0,2,4,6,8,10], the progress goes from 0 to 4 directly and tick mark 2 is skipped. Similarly, if i have tick marks as [0,3,6,9,12,15], then the progress jumps directly from 0 to 9 and tick mark 3 and 6 are skipped. The code i use is:


 seekBar = IndicatorSeekBar.with(mContext)
                            .indicatorColor(ContextCompat.getColor(mContext, R.color.transparent))
                            .indicatorContentViewLayoutId(R.layout.isb_indicator)
                            .indicatorTextColor(ContextCompat.getColor(mContext, R.color.black))
                            .indicatorTextSize(14)
                            .showIndicatorType(IndicatorType.ROUNDED_RECTANGLE)
                            .thumbDrawable(ContextCompat.getDrawable(mContext, R.drawable.tick))
                            .trackBackgroundColor(ContextCompat.getColor(mContext, R.color.transparent))
                            .trackBackgroundSize(5)
                            .trackProgressColor(ContextCompat.getColor(mContext, R.color.colorPrimaryDark))
                            .trackProgressSize(5)
                            .trackRoundedCorners(true)
                            .showTickTexts(true)
                            .min(0)
                            .max(10)
                            .tickTextsColor(ContextCompat.getColor(mContext, R.color.grey))
                            .tickMarksDrawable(null)
                            .tickCount(6)
                            .build();

LinearLayout.LayoutParams param = new LinearLayout.LayoutParams(0, LinearLayout.LayoutParams.WRAP_CONTENT,1);
            seekBar.setLayoutParams(param);

            if (isContinuous)
                seekBar.setIndicatorTextFormat("${PROGRESS}%");
            else
                seekBar.setIndicatorTextFormat("${TICK_TEXT}");

            LinearLayout seekLayout = view.findViewById(R.id.seek_ll);
            seekLayout.addView(seekBar, 0);

**Comment by ankuranurag2** [comment]
The issue  which i mentioned in second comment is gone by removing weight, but the first issue is still there. The progress changes automatically when keyboard appears. It happens with tick mark [2,6,10] but not with [0,4,8].  The strange thing is that there is no callback to seekChangeListener. None of the function in code is called. I think the issue is with the view itself.

**Comment by ankuranurag2** [comment]
The issue was being caused beacuse i was calling seekbar.setMax() again in the code where max value was different from the previous max value. Thanks
