### ISSUE TITLE
No java implementation of `app:isb_user_seekable="false"`

### ISSUE THREAD

**Issue by JadenGu** [warkiz/IndicatorSeekBar#83]
Hi,

I found the `app:isb_user_seekable="false"` cannot be written in Java code, no corresponding method found.  
Just forgot adding this feature? Thx.

**Comment by borosuman** [comment]
Try this.
` yourSeekBar.forbidUserToSeek(true);`

**Comment by JadenGu** [comment]
No this method either when using version 2.0.8

**Comment by warkiz** [comment]
Hi @JadenGu The latest version open this api.
Usage like : seekbar.setUserSeekAble(true); 
If it is helpful to you, please help close this issue. thanks.

Hi @borosuman ,  the method you mentioned exited in V1 only, It was been deprecated as a big change in V2.

Many thanks for both of you.

**Comment by JadenGu** [comment]
Thanks a lot.
