### ISSUE TITLE
how to create Rang bar Like below image 

### ISSUE THREAD

**Issue by erishiraj** [warkiz/IndicatorSeekBar#84]
Hi,
I am Trying for range bar like below image is this possible.
thanks in Advance.
![screen shot 2018-06-26 at 2 57 43 pm](https://user-images.githubusercontent.com/27275294/41902777-e892799c-7951-11e8-80e5-46ff84940096.png)

**Comment by warkiz** [comment]
Sorry for this, it is not support on this library.
