### ISSUE TITLE
How to set indicator with image?

### ISSUE THREAD

**Issue by goffity** [warkiz/IndicatorSeekBar#87]
How can I set indicator with image drawable.

**Comment by goffity** [comment]
Update:
I Fixed it by change to user layout file and add image view inside that.

Is possible to set indicator view with image?

**Comment by warkiz** [comment]
hi @goffity ,certainly yes.
If you want to replace all the Indicator view , you can do by : 
seekbar.getIndicator.setContentView(your view with image);

If you want to keep the arrow under indicator, you can do by:
seekbar.getIndicator.setTopContentView(your view with image);
