### ISSUE TITLE
Can's set tickCount programmatically.

### ISSUE THREAD

**Issue by skkirtonia** [warkiz/IndicatorSeekBar#90]
rating_seekbar =(IndicatorSeekBar) findViewById(R.id.rating_seekbar);
rating_seekbar.setMin(40);
rating_seekbar.setMax(200);
rating_seekbar.setProgress(100);

**Comment by Nyariki** [comment]
Let me create a PR

**Comment by denvernexus** [comment]
+1

**Comment by gavaliswapnil** [comment]
How to set tickCount programatically?

**Comment by mohamedma872** [comment]
i'm facing the same issue
