### ISSUE TITLE
How to set track rounded corners only outside track.

### ISSUE THREAD

**Issue by goffity** [warkiz/IndicatorSeekBar#92]
I try to set rounded track.
I use `isb_track_rounded_corners="true"`, but it set rounded inside seekbar too.
![screen shot 2561-07-14 at 15 10 31](https://user-images.githubusercontent.com/778547/42722556-142d6880-8778-11e8-9c39-812b02851aee.png)

How to set round only start and end of seekbar.

**Comment by warkiz** [comment]
Sorry，no support this.
