### ISSUE TITLE
Can i set progress to exact number in between seekbar sections.

### ISSUE THREAD

**Issue by jishantmed** [warkiz/IndicatorSeekBar#94]
![discrete_1](https://user-images.githubusercontent.com/41432242/42986549-96da0406-8c13-11e8-9d79-0641c9eea3cd.png)

I want to set progress in between 60 and 40 it could be any number .But when i set on 49 it set on 40 and when i set on 57 it set on 60,
Is that possible to set on exact particular number ?

**Comment by warkiz** [comment]
@jishantmed yes , please see the latest version which is provided attr isb_thumb_adjust_auto =  false 
, or by java code indicatorSeekbar.setThumbAdjustAuto(false)
